services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        ICE_APT_PACKAGE: zeroc-ice-all-dev
    image: servant-management-server:java25
    ports:
      - "10000:10000"

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: servant-management-client:python-latest
    depends_on:
      - server
    stdin_open: true
    tty: true
